# cargo-deny configuration for Claudia Statusline
# This file configures supply chain security checks

[bans]
# Warn about multiple versions of the same crate
multiple-versions = "warn"
# Allow workspace members to use different versions
workspace-default-features = "allow"
# Crates to skip when checking for duplicates
skip = []
skip-tree = []

[licenses]
# Deny crates with no license
unlicensed = "deny"
# Allow only these licenses (permissive)
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Unlicense",
]
# Deny copyleft licenses (e.g., GPL/AGPL)
copyleft = "deny"
# Confidence threshold for license detection
confidence-threshold = 0.8

[sources]
# Warn about crates from unknown registries
unknown-registry = "warn"
# Warn about crates from unknown git sources
unknown-git = "warn"
# Allow git sources from these organizations
allow-git = [
    "https://github.com/rust-lang",
    "https://github.com/rusqlite",
]

[advisories]
# Path to the advisory database
db-path = "~/.cargo/advisory-db"
# URLs to advisory databases
db-urls = ["https://github.com/rustsec/advisory-db"]
# Warn about yanked crates
yanked = "warn"
# Maximum allowed severity for vulnerabilities
vulnerability = "deny"
# Allow unmaintained crates with a warning
unmaintained = "warn"
# Security notice behavior
notice = "warn"
# Ignore specific advisories (use sparingly)
ignore = [
    # Example: "RUSTSEC-2020-0001",
]
